# -*- coding: utf-8 -*-
"""
Script 04 — Aggregate charging demand by origin zone.

Groups all stop/rest events by their origin NUTS-3 zone and sums the demand
columns, then attaches the zone centroid geometry to produce a point layer
with one feature per origin zone.

Output (origin_zone_demand.shp):
  ID_origin_  — ETISPlus zone ID
  DTN30_100   — total daily trucks needing a charge at 100% EV penetration
  DTN30_M15   — total daily trucks needing a charge at 15% EV penetration
  ChaEnekWh   — total energy charged (kWh) at 100% EV penetration
  ChaEM15     — total energy charged (kWh) at 15% EV penetration
  Rest        — total rest-stop events departing from this origin
  Break       — total break-stop events departing from this origin

This output answers "how much EV charging demand is generated by freight
departing from each region?" and is useful for regional infrastructure
planning and policy analysis.
"""

import os
import sys
import time

import geopandas as gpd
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import (
    STOP_REST_FILE, CENTROIDS_SHP, BASE_OUTPUT_DIR,
    EV_SHARE_MAIN,
)

OUTPUT_FILE = os.path.join(BASE_OUTPUT_DIR, 'origin_zone_demand.shp')


if __name__ == '__main__':
    t0 = time.time()

    print('Loading stop/rest events...')
    needed = ['ID_origin_', 'DTN30_100', 'ChaEnekWh', 'Rest', 'Break']
    try:
        rb = gpd.read_file(STOP_REST_FILE, columns=needed, ignore_geometry=True)
    except TypeError:
        rb = gpd.read_file(STOP_REST_FILE)
        rb = pd.DataFrame(rb[needed])

    rb['Rest']  = rb['Rest'].astype(int)
    rb['Break'] = rb['Break'].astype(int)
    print('  {:,} rows, {:,} unique origins'.format(
        len(rb), rb['ID_origin_'].nunique()))

    grouped = (
        rb.groupby('ID_origin_')[['DTN30_100', 'ChaEnekWh', 'Rest', 'Break']]
        .sum()
        .reset_index()
    )
    grouped['DTN30_M15'] = grouped['DTN30_100'] * EV_SHARE_MAIN
    grouped['ChaEM15']   = grouped['ChaEnekWh'] * EV_SHARE_MAIN

    print('Loading centroids...')
    centroids = gpd.read_file(CENTROIDS_SHP)[['ETISPlus_Z', 'geometry']]
    centroids = centroids.rename(columns={'ETISPlus_Z': 'ID_origin_'})

    result = centroids.merge(grouped, on='ID_origin_', how='inner')
    result = gpd.GeoDataFrame(result, geometry='geometry', crs=centroids.crs)

    col_order = ['ID_origin_', 'DTN30_100', 'DTN30_M15', 'ChaEnekWh',
                 'ChaEM15', 'Rest', 'Break', 'geometry']
    result = result[[c for c in col_order if c in result.columns]]

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    result.to_file(OUTPUT_FILE)
    print('  {:,} origin points saved: {}'.format(
        len(result), os.path.basename(OUTPUT_FILE)))

    print('\nDone in {:.2f} minutes'.format((time.time() - t0) / 60))
